name: Trigger Codeforces Script Workflow

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token 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" \
            https://api.github.com/repos/sreegithub19/codeforces_script/dispatches \
            -d '{"event_type": "trigger-codeforces-script"}'
