name: Run Gitlab

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Run Gitlab script
        run: |
          git clone https://gitlab.com/sreegithub19/first_repo.git
          cd first_repo
          ls -la
          python hello.py 
